-- Assam Drive Supabase foundation
-- Apply this migration in the Assam Drive Supabase SQL editor.
create table if not exists public.profiles(
 id uuid primary key references auth.users(id) on delete cascade,
 role text not null check(role in('CUSTOMER','DRIVER')),
 full_name text not null default '',
 phone text not null default '',
 avatar_url text,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
create table if not exists public.driver_profiles(
 id uuid primary key references public.profiles(id) on delete cascade,
 vehicle_type text not null check(vehicle_type in('BIKE','AUTO','CAR')),
 registration_number text not null default '',
 date_of_birth date,
 verification_status text not null default 'PENDING' check(verification_status in('PENDING','UNDER_REVIEW','APPROVED','REJECTED','SUSPENDED')),
 verified boolean not null default false,
 online boolean not null default false,
 emergency_contact text,
 upi_id text,
 driver_id text unique,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
create table if not exists public.driver_documents(
 id bigint generated by default as identity primary key,
 driver_id uuid not null references public.driver_profiles(id) on delete cascade,
 document_type text not null,
 storage_path text not null,
 document_name text,
 expires_on date,
 automated_status text not null default 'PENDING' check(automated_status in('PENDING','MATCH','MISMATCH','EXPIRED','SUSPECTED')),
 admin_status text not null default 'PENDING' check(admin_status in('PENDING','APPROVED','REJECTED')),
 created_at timestamptz not null default now()
);
create table if not exists public.rides(
 id bigint generated by default as identity primary key,
 customer_id uuid not null references public.profiles(id),
 driver_id uuid references public.driver_profiles(id),
 vehicle_type text not null check(vehicle_type in('BIKE','AUTO','CAR')),
 pickup_text text not null,destination_text text not null,
 pickup_lat double precision,pickup_lng double precision,destination_lat double precision,destination_lng double precision,
 distance_km numeric(10,2) not null default 0,duration_minutes integer not null default 0,fare numeric(12,2) not null default 0,
 status text not null default 'SEARCHING',driver_phone_snapshot text,created_at timestamptz not null default now()
);
alter table public.profiles enable row level security;
alter table public.driver_profiles enable row level security;
alter table public.driver_documents enable row level security;
alter table public.rides enable row level security;
drop policy if exists profiles_own on public.profiles;
create policy profiles_own on public.profiles for all using(auth.uid()=id) with check(auth.uid()=id);
drop policy if exists driver_profile_own on public.driver_profiles;
create policy driver_profile_own on public.driver_profiles for all using(auth.uid()=id) with check(auth.uid()=id);
drop policy if exists driver_docs_own on public.driver_documents;
create policy driver_docs_own on public.driver_documents for all using(auth.uid()=driver_id) with check(auth.uid()=driver_id);
drop policy if exists rides_customer_or_driver on public.rides;
create policy rides_customer_or_driver on public.rides for select using(auth.uid()=customer_id or auth.uid()=driver_id);
drop policy if exists rides_customer_insert on public.rides;
create policy rides_customer_insert on public.rides for insert with check(auth.uid()=customer_id);
-- Keep driver approval/admin operations server-side; do not expose admin policies to anon/authenticated clients.
