-- Assam Drive: production driver document verification
create table if not exists public.driver_documents(
 id bigint generated by default as identity primary key,
 driver_id uuid not null references public.driver_profiles(id) on delete cascade,
 document_type text not null,
 storage_path text not null,
 original_filename text,
 mime_type text,
 file_size bigint,
 sha256 text,
 expires_on date,
 ocr_text text,
 extracted_name text,
 name_match_score numeric(5,2),
 authenticity_status text not null default 'PENDING' check(authenticity_status in('PENDING','PASS','SUSPICIOUS','FAILED','UNVERIFIED')),
 automated_status text not null default 'PENDING' check(automated_status in('PENDING','MATCH','MISMATCH','EXPIRED','SUSPECTED')),
 admin_status text not null default 'PENDING' check(admin_status in('PENDING','APPROVED','REJECTED')),
 review_notes text,
 reviewed_by uuid,
 reviewed_at timestamptz,
 created_at timestamptz not null default now()
);
alter table public.driver_documents
 add column if not exists original_filename text,
 add column if not exists mime_type text,
 add column if not exists file_size bigint,
 add column if not exists sha256 text,
 add column if not exists ocr_text text,
 add column if not exists extracted_name text,
 add column if not exists name_match_score numeric(5,2),
 add column if not exists authenticity_status text not null default 'PENDING',
 add column if not exists review_notes text,
 add column if not exists reviewed_by uuid,
 add column if not exists reviewed_at timestamptz;
alter table public.driver_documents enable row level security;
drop policy if exists driver_documents_owner_read on public.driver_documents;
create policy driver_documents_owner_read on public.driver_documents for select using(auth.uid()=driver_id);
drop policy if exists driver_documents_owner_insert on public.driver_documents;
create policy driver_documents_owner_insert on public.driver_documents for insert with check(auth.uid()=driver_id);
-- Admin writes must happen through the protected Edge Function, not the browser.
create index if not exists driver_documents_status_idx on public.driver_documents(admin_status,automated_status);
