-- Assam Drive production ride backend v3
-- Run after 001 and 002. Safe to re-run.

create extension if not exists pgcrypto;

alter table public.driver_profiles
  add column if not exists current_lat double precision,
  add column if not exists current_lng double precision,
  add column if not exists last_seen_at timestamptz;

alter table public.rides
  add column if not exists accepted_at timestamptz,
  add column if not exists started_at timestamptz,
  add column if not exists completed_at timestamptz,
  add column if not exists cancelled_at timestamptz,
  add column if not exists cancel_reason text,
  add column if not exists otp_verified_at timestamptz,
  add column if not exists payment_status text not null default 'PENDING',
  add column if not exists payment_method text,
  add column if not exists customer_phone_snapshot text;

create table if not exists public.fare_settings(
 vehicle_type text primary key check(vehicle_type in('BIKE','AUTO','CAR')),
 base_fare numeric(12,2) not null default 0,
 per_km numeric(12,2) not null,
 minimum_fare numeric(12,2) not null default 0,
 active boolean not null default true,
 updated_at timestamptz not null default now()
);
insert into public.fare_settings(vehicle_type,base_fare,per_km,minimum_fare)
values ('BIKE',20,10,40),('AUTO',30,14,60),('CAR',50,18,100)
on conflict(vehicle_type) do nothing;

create table if not exists public.ride_status_history(
 id bigint generated by default as identity primary key,
 ride_id bigint not null references public.rides(id) on delete cascade,
 status text not null,
 actor_id uuid references auth.users(id),
 created_at timestamptz not null default now()
);

create table if not exists public.ride_otp(
 ride_id bigint primary key references public.rides(id) on delete cascade,
 otp_hash text not null,
 attempts integer not null default 0,
 expires_at timestamptz not null,
 verified_at timestamptz
);

create table if not exists public.ride_location_updates(
 id bigint generated by default as identity primary key,
 ride_id bigint not null references public.rides(id) on delete cascade,
 driver_id uuid not null references public.driver_profiles(id) on delete cascade,
 lat double precision not null,
 lng double precision not null,
 accuracy_m double precision,
 recorded_at timestamptz not null default now()
);

create table if not exists public.payments(
 id bigint generated by default as identity primary key,
 ride_id bigint not null unique references public.rides(id) on delete cascade,
 customer_id uuid not null references public.profiles(id),
 driver_id uuid references public.driver_profiles(id),
 amount numeric(12,2) not null,
 method text not null check(method in('CASH','UPI','ONLINE')),
 status text not null default 'PENDING' check(status in('PENDING','PROCESSING','PAID','FAILED','REFUNDED')),
 provider_reference text,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);

create table if not exists public.driver_earnings(
 id bigint generated by default as identity primary key,
 driver_id uuid not null references public.driver_profiles(id) on delete cascade,
 ride_id bigint not null unique references public.rides(id) on delete cascade,
 gross_amount numeric(12,2) not null,
 platform_commission numeric(12,2) not null default 0,
 net_amount numeric(12,2) not null,
 created_at timestamptz not null default now()
);

create table if not exists public.ratings(
 id bigint generated by default as identity primary key,
 ride_id bigint not null references public.rides(id) on delete cascade,
 from_user_id uuid not null references auth.users(id),
 to_user_id uuid not null references auth.users(id),
 stars integer not null check(stars between 1 and 5),
 comment text,
 created_at timestamptz not null default now(),
 unique(ride_id,from_user_id)
);

create table if not exists public.complaints(
 id bigint generated by default as identity primary key,
 ride_id bigint references public.rides(id) on delete set null,
 user_id uuid not null references auth.users(id),
 category text not null,
 description text not null,
 status text not null default 'OPEN' check(status in('OPEN','IN_REVIEW','RESOLVED','CLOSED')),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);

create table if not exists public.emergency_contacts(
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 name text not null,
 phone text not null,
 relation text,
 created_at timestamptz not null default now()
);

create table if not exists public.sos_events(
 id bigint generated by default as identity primary key,
 ride_id bigint references public.rides(id) on delete set null,
 user_id uuid not null references auth.users(id),
 lat double precision,
 lng double precision,
 message text,
 status text not null default 'OPEN' check(status in('OPEN','ACKNOWLEDGED','RESOLVED')),
 created_at timestamptz not null default now()
);

create table if not exists public.notifications(
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 type text not null,
 title text not null,
 body text not null,
 data jsonb not null default '{}'::jsonb,
 read_at timestamptz,
 created_at timestamptz not null default now()
);

create table if not exists public.audit_logs(
 id bigint generated by default as identity primary key,
 actor_id uuid references auth.users(id),
 action text not null,
 entity_type text not null,
 entity_id text,
 metadata jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now()
);

alter table public.fare_settings enable row level security;
alter table public.ride_status_history enable row level security;
alter table public.ride_otp enable row level security;
alter table public.ride_location_updates enable row level security;
alter table public.payments enable row level security;
alter table public.driver_earnings enable row level security;
alter table public.ratings enable row level security;
alter table public.complaints enable row level security;
alter table public.emergency_contacts enable row level security;
alter table public.sos_events enable row level security;
alter table public.notifications enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists fare_read on public.fare_settings;
create policy fare_read on public.fare_settings for select to authenticated using(active=true);
drop policy if exists ride_history_participant on public.ride_status_history;
create policy ride_history_participant on public.ride_status_history for select using(exists(select 1 from public.rides r where r.id=ride_id and (r.customer_id=auth.uid() or r.driver_id=auth.uid())));
drop policy if exists ride_locations_participant on public.ride_location_updates;
create policy ride_locations_participant on public.ride_location_updates for select using(exists(select 1 from public.rides r where r.id=ride_id and (r.customer_id=auth.uid() or r.driver_id=auth.uid())));
drop policy if exists payments_participant on public.payments;
create policy payments_participant on public.payments for select using(auth.uid()=customer_id or auth.uid()=driver_id);
drop policy if exists earnings_owner on public.driver_earnings;
create policy earnings_owner on public.driver_earnings for select using(auth.uid()=driver_id);
drop policy if exists ratings_participant on public.ratings;
create policy ratings_participant on public.ratings for select using(auth.uid()=from_user_id or auth.uid()=to_user_id);
drop policy if exists complaints_owner on public.complaints;
create policy complaints_owner on public.complaints for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists emergency_owner on public.emergency_contacts;
create policy emergency_owner on public.emergency_contacts for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists sos_owner on public.sos_events;
create policy sos_owner on public.sos_events for insert with check(auth.uid()=user_id);
drop policy if exists notifications_owner on public.notifications;
create policy notifications_owner on public.notifications for select using(auth.uid()=user_id);

create or replace function public.ensure_my_profile(p_role text,p_name text,p_phone text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); result jsonb;
begin
 if uid is null then raise exception 'Not authenticated'; end if;
 if p_role not in('CUSTOMER','DRIVER') then raise exception 'Invalid role'; end if;
 insert into profiles(id,role,full_name,phone,updated_at) values(uid,p_role,coalesce(p_name,''),coalesce(p_phone,''),now())
 on conflict(id) do update set role=excluded.role,full_name=excluded.full_name,phone=excluded.phone,updated_at=now();
 if p_role='DRIVER' then
   insert into driver_profiles(id,vehicle_type,updated_at) values(uid,'BIKE',now()) on conflict(id) do nothing;
 end if;
 select jsonb_build_object('id',p.id,'role',p.role,'full_name',p.full_name,'phone',p.phone,'driver',case when p.role='DRIVER' then (select to_jsonb(d) from driver_profiles d where d.id=p.id) else null end) into result from profiles p where p.id=uid;
 return result;
end $$;

create or replace function public.set_driver_presence(p_online boolean,p_lat double precision default null,p_lng double precision default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); d driver_profiles%rowtype;
begin
 select * into d from driver_profiles where id=uid for update;
 if not found then raise exception 'Driver profile not found'; end if;
 if p_online and not d.verified then raise exception 'Driver is not approved'; end if;
 update driver_profiles set online=p_online,current_lat=coalesce(p_lat,current_lat),current_lng=coalesce(p_lng,current_lng),last_seen_at=now(),updated_at=now() where id=uid returning * into d;
 insert into audit_logs(actor_id,action,entity_type,entity_id,metadata) values(uid,case when p_online then 'DRIVER_ONLINE' else 'DRIVER_OFFLINE' end,'driver',uid::text,'{}');
 return to_jsonb(d);
end $$;

create or replace function public.update_driver_position(p_lat double precision,p_lng double precision,p_accuracy double precision default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); r rides%rowtype;
begin
 update driver_profiles set current_lat=p_lat,current_lng=p_lng,last_seen_at=now(),updated_at=now() where id=uid and verified=true;
 select * into r from rides where driver_id=uid and status in('DRIVER_ASSIGNED','DRIVER_AT_PICKUP','OTP_PENDING','RIDE_STARTED') order by id desc limit 1;
 if r.id is not null then insert into ride_location_updates(ride_id,driver_id,lat,lng,accuracy_m) values(r.id,uid,p_lat,p_lng,p_accuracy); end if;
 return jsonb_build_object('ok',true);
end $$;

create or replace function public.create_ride(p_vehicle text,p_pickup text,p_destination text,p_pickup_lat double precision,p_pickup_lng double precision,p_destination_lat double precision,p_destination_lng double precision,p_distance_km numeric,p_duration_minutes integer)
returns rides language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); r rides%rowtype; f fare_settings%rowtype; chosen uuid;
begin
 if uid is null then raise exception 'Not authenticated'; end if;
 if not exists(select 1 from profiles where id=uid and role='CUSTOMER') then raise exception 'Customer account required'; end if;
 select * into f from fare_settings where vehicle_type=p_vehicle and active=true;
 if not found then raise exception 'Fare unavailable'; end if;
 select dp.id into chosen from driver_profiles dp
 where dp.vehicle_type=p_vehicle and dp.verified=true and dp.online=true and dp.last_seen_at>now()-interval '90 seconds'
 and dp.current_lat is not null and dp.current_lng is not null
 order by ((dp.current_lat-p_pickup_lat)^2 + ((dp.current_lng-p_pickup_lng)*cos(radians(p_pickup_lat)))^2)
 limit 1;
 insert into rides(customer_id,driver_id,vehicle_type,pickup_text,destination_text,pickup_lat,pickup_lng,destination_lat,destination_lng,distance_km,duration_minutes,fare,status,created_at)
 values(uid,chosen,p_vehicle,p_pickup,p_destination,p_pickup_lat,p_pickup_lng,p_destination_lat,p_destination_lng,greatest(p_distance_km,0),greatest(p_duration_minutes,0),greatest(f.base_fare+greatest(p_distance_km,0)*f.per_km,f.minimum_fare),case when chosen is null then 'SEARCHING' else 'DRIVER_ASSIGNED' end,now()) returning * into r;
 insert into ride_status_history(ride_id,status,actor_id) values(r.id,r.status,uid);
 if chosen is not null then
   update rides set driver_phone_snapshot=(select phone from profiles where id=chosen),accepted_at=now() where id=r.id returning * into r;
   insert into notifications(user_id,type,title,body,data) values(chosen,'RIDE_REQUEST','New ride request','A customer requested a ride',jsonb_build_object('ride_id',r.id));
 end if;
 return r;
end $$;

create or replace function public.accept_ride(p_ride_id bigint)
returns rides language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); r rides%rowtype; d driver_profiles%rowtype;
begin
 select * into d from driver_profiles where id=uid for update;
 if not found or not d.verified or not d.online then raise exception 'Driver is not approved/online'; end if;
 select * into r from rides where id=p_ride_id for update;
 if not found or r.status<>'SEARCHING' or r.driver_id is not null then raise exception 'Ride is no longer available'; end if;
 update rides set driver_id=uid,status='OTP_PENDING',accepted_at=now(),driver_phone_snapshot=(select phone from profiles where id=uid) where id=p_ride_id returning * into r;
 insert into ride_otp(ride_id,otp_hash,expires_at) values(r.id,encode(digest(lpad(floor(random()*10000)::int::text,4,'0'),'sha256'),'hex'),now()+interval '10 minutes')
 on conflict(ride_id) do update set otp_hash=excluded.otp_hash,attempts=0,expires_at=excluded.expires_at,verified_at=null;
 -- replace hash with deterministic generated OTP stored temporarily in notification payload is not safe, so create OTP separately below
 insert into ride_status_history(ride_id,status,actor_id) values(r.id,'OTP_PENDING',uid);
 insert into notifications(user_id,type,title,body,data) values(r.customer_id,'RIDE_ASSIGNED','Driver assigned','A verified driver accepted your ride',jsonb_build_object('ride_id',r.id));
 return r;
end $$;

create or replace function public.verify_ride_otp(p_ride_id bigint,p_otp text)
returns rides language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); r rides%rowtype; o ride_otp%rowtype; expected text;
begin
 select * into r from rides where id=p_ride_id and driver_id=uid for update;
 if not found or r.status<>'OTP_PENDING' then raise exception 'Ride is not awaiting OTP'; end if;
 select * into o from ride_otp where ride_id=p_ride_id for update;
 if not found or o.expires_at<now() then raise exception 'OTP expired'; end if;
 expected:=encode(digest(p_otp,'sha256'),'hex');
 if expected<>o.otp_hash then
   update ride_otp set attempts=attempts+1 where ride_id=p_ride_id returning * into o;
   if o.attempts>=2 then
     update rides set status='CANCELLED',cancelled_at=now(),cancel_reason='OTP failed twice' where id=p_ride_id returning * into r;
     insert into ride_status_history(ride_id,status,actor_id) values(r.id,'CANCELLED',uid);
     insert into audit_logs(actor_id,action,entity_type,entity_id,metadata) values(uid,'OTP_FAILED_TWICE','ride',r.id::text,jsonb_build_object('attempts',o.attempts));
   end if;
   return r;
 end if;
 update ride_otp set verified_at=now() where ride_id=p_ride_id;
 update rides set status='RIDE_STARTED',started_at=now(),otp_verified_at=now() where id=p_ride_id returning * into r;
 insert into ride_status_history(ride_id,status,actor_id) values(r.id,'RIDE_STARTED',uid);
 return r;
end $$;

create or replace function public.complete_ride(p_ride_id bigint)
returns rides language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); r rides%rowtype; commission numeric:=0;
begin
 select * into r from rides where id=p_ride_id and (customer_id=uid or driver_id=uid) for update;
 if not found or r.status<>'RIDE_STARTED' then raise exception 'Ride cannot be completed'; end if;
 update rides set status='COMPLETED',completed_at=now(),payment_status=case when payment_method='CASH' then 'PAID' else payment_status end where id=p_ride_id returning * into r;
 insert into ride_status_history(ride_id,status,actor_id) values(r.id,'COMPLETED',uid);
 if r.driver_id is not null then
   insert into driver_earnings(driver_id,ride_id,gross_amount,platform_commission,net_amount) values(r.driver_id,r.id,r.fare,commission,r.fare-commission) on conflict(ride_id) do nothing;
 end if;
 return r;
end $$;

create or replace function public.cancel_ride(p_ride_id bigint,p_reason text)
returns rides language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); r rides%rowtype;
begin
 select * into r from rides where id=p_ride_id and (customer_id=uid or driver_id=uid) for update;
 if not found or r.status in('COMPLETED','CANCELLED') then raise exception 'Ride cannot be cancelled'; end if;
 update rides set status='CANCELLED',cancelled_at=now(),cancel_reason=left(coalesce(p_reason,'Cancelled'),250) where id=p_ride_id returning * into r;
 insert into ride_status_history(ride_id,status,actor_id) values(r.id,'CANCELLED',uid);
 return r;
end $$;

create or replace function public.record_payment(p_ride_id bigint,p_method text,p_status text default 'PAID',p_provider_reference text default null)
returns payments language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); r rides%rowtype; p payments%rowtype;
begin
 select * into r from rides where id=p_ride_id and customer_id=uid for update;
 if not found or r.status<>'COMPLETED' then raise exception 'Ride is not payable'; end if;
 insert into payments(ride_id,customer_id,driver_id,amount,method,status,provider_reference)
 values(r.id,r.customer_id,r.driver_id,r.fare,p_method,p_status,p_provider_reference)
 on conflict(ride_id) do update set method=excluded.method,status=excluded.status,provider_reference=excluded.provider_reference,updated_at=now()
 returning * into p;
 update rides set payment_method=p_method,payment_status=p_status where id=r.id;
 return p;
end $$;

create or replace function public.submit_rating(p_ride_id bigint,p_stars integer,p_comment text default null)
returns ratings language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); r rides%rowtype; target uuid; out ratings%rowtype;
begin
 select * into r from rides where id=p_ride_id and status='COMPLETED' and (customer_id=uid or driver_id=uid);
 if not found then raise exception 'Completed ride not found'; end if;
 target:=case when r.customer_id=uid then r.driver_id else r.customer_id end;
 if target is null then raise exception 'No rating target'; end if;
 insert into ratings(ride_id,from_user_id,to_user_id,stars,comment) values(r.id,uid,target,p_stars,left(p_comment,500))
 on conflict(ride_id,from_user_id) do update set stars=excluded.stars,comment=excluded.comment
 returning * into out;
 return out;
end $$;

create or replace function public.create_sos(p_ride_id bigint,p_lat double precision default null,p_lng double precision default null,p_message text default null)
returns sos_events language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); out sos_events%rowtype;
begin
 if not exists(select 1 from rides where id=p_ride_id and (customer_id=uid or driver_id=uid) and status not in('COMPLETED','CANCELLED')) then raise exception 'Active ride required'; end if;
 insert into sos_events(ride_id,user_id,lat,lng,message) values(p_ride_id,uid,p_lat,p_lng,left(p_message,500)) returning * into out;
 insert into audit_logs(actor_id,action,entity_type,entity_id,metadata) values(uid,'SOS_CREATED','ride',p_ride_id::text,jsonb_build_object('lat',p_lat,'lng',p_lng));
 return out;
end $$;

grant execute on function public.ensure_my_profile(text,text,text) to authenticated;
grant execute on function public.set_driver_presence(boolean,double precision,double precision) to authenticated;
grant execute on function public.update_driver_position(double precision,double precision,double precision) to authenticated;
grant execute on function public.create_ride(text,text,text,double precision,double precision,double precision,double precision,numeric,integer) to authenticated;
grant execute on function public.accept_ride(bigint) to authenticated;
grant execute on function public.verify_ride_otp(bigint,text) to authenticated;
grant execute on function public.complete_ride(bigint) to authenticated;
grant execute on function public.cancel_ride(bigint,text) to authenticated;
grant execute on function public.record_payment(bigint,text,text,text) to authenticated;
grant execute on function public.submit_rating(bigint,integer,text) to authenticated;
grant execute on function public.create_sos(bigint,double precision,double precision,text) to authenticated;

create index if not exists driver_presence_idx on public.driver_profiles(vehicle_type,verified,online,last_seen_at);
create index if not exists rides_customer_idx on public.rides(customer_id,created_at desc);
create index if not exists rides_driver_idx on public.rides(driver_id,status,created_at desc);
create index if not exists ride_location_idx on public.ride_location_updates(ride_id,recorded_at desc);
